name: Docker Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        env:
          TAG: ${{  github.ref_name }}
          REPO: ${{ github.repository }}
        run: |
          docker build -t ${REPO}:latest .
          docker tag ${REPO}:latest ${REPO}:${TAG}
          docker push ${REPO}:${TAG}
          docker push ${REPO}:latest